[package]
name = "orgo_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
serde_json = "1.0.138"
strum_macros = "0.26.4"
thiserror = "1.0.62"
